### PR TITLE
Fix ItemStack memory leak

### LINKED ISSUE #1884: Crafting a pickaxe, dropping it and immediately picking it back up causes a memory leak

### PR DESCRIPTION
**Pull request by psznm**
Closes #1884

### CODE REVIEW

File: src/items.zig [hunk 1]
```diff
@@ -1036,7 +1036,10 @@ pub const ItemStack = struct { // MARK: ItemStack
 	}
 
 	pub fn clear(self: *ItemStack) void {
-		self.item = null;
+		if(self.item) |item| {
+			item.deinit();
+			self.item = null;
+		}
```
Comment (IntegratedQuantum) [inline src/items.zig]: The clear function was never supposed to deinit things. Most code assumes this so this might actually cause other problems elsewhere.

Instead I'd suggest to remove the clear function entirely and replace it with ` = .{};` which is more explicit about what it does and doesn't do.

**Review by IntegratedQuantum — CHANGES_REQUESTED** [review]

File: src/items.zig (hunk 1 above)
Comment (psznm) [reply src/items.zig]: Yes, it is really way more clear now. (pun not intended)

I removed clear, and added deinit where it missing was causing issue #1884. Not 100% positive that missing deinit in other cases do not cause issues too.

File: src/items.zig [hunk 2]
```diff
@@ -1020,6 +1020,7 @@ pub const ItemStack = struct { // MARK: ItemStack
 	pub fn deinit(self: *ItemStack) void {
 		if(self.item) |item| {
 			item.deinit();
+			self.item = null;
```
Comment (IntegratedQuantum) [inline src/items.zig]: unnecessary, things must not be used without reinitializing after deinit.
If you want to add a safety check then set `self.* = undefined;`

**Review by IntegratedQuantum — CHANGES_REQUESTED** [review]

File: src/items.zig (hunk 2 above)
Comment (psznm) [reply src/items.zig]: Removed.

**Review by IntegratedQuantum — APPROVED** [review]
