### PR TITLE
Print an error when biome radius is smaller than grid resolution

### LINKED ISSUE #1864: Print an error if a biome radius is smaller than the resolution of the underlying grid.
People keep getting this wrong.

### PR DESCRIPTION
**Pull request by yel0h**
Adds a check in `Biome.init` to validate each registered biome's radius. When the radius is smaller than half of `terrain.SurfaceMap.MapFragment.biomeSize` prints an error informing the biome's creator of valid radius values.

This resolves #1864. Note: currently prints
`Biome cubyz:prairie/limestone_pit has radius 9, smaller than grid resolution. It should be at least 16`
due to an invalid radius set for that biome.

### CODE REVIEW

**Review by IntegratedQuantum — CHANGES_REQUESTED** [review]
Please fix the biome that is producing errors. We should not have any error logs in master.

**Comment by yel0h** [comment]
Alright, I modified the biome so that its radius is 16, while keeping its radius variation. Also tried to adjust its chance accordingly.

File: src/server/terrain/biomes.zig [hunk 1]
```diff
@@ -355,6 +355,9 @@ pub const Biome = struct { // MARK: Biome
 			.chance = zon.get(f32, "chance", if(zon == .null) 0 else 1),
 			.maxSubBiomeCount = zon.get(f32, "maxSubBiomeCount", std.math.floatMax(f32)),
 		};
+		if(self.radius < terrain.SurfaceMap.MapFragment.biomeSize/2) {
```
Comment (IntegratedQuantum) [inline src/server/terrain/biomes.zig]: Should check the min radius.

File: assets/cubyz/biomes/prairie/limestone_pit.zig.zon [hunk 2]
```diff
@@ -14,7 +14,7 @@
 	.parentBiomes = .{
 		.{
 			.id = "cubyz:prairie/base",
-			.chance = 24,
+			.chance = 14,
```
Comment (IntegratedQuantum) [inline assets/cubyz/biomes/prairie/limestone_pit.zig.zon]: Based on math alone, the chance should decrease by the area increase → down to 20% in this case.

**Comment by yel0h** [comment]
Okay, I made it check `minRadius` and added another check to validate the `minRadius`/`maxRadius` range, and I also adjusted the radius and chance again, hopefully correctly (this time decreased it in proportion to the area change).

**Review by IntegratedQuantum — APPROVED** [review]
