### PR TITLE
Authentication

### LINKED ISSUE #1736: The game cannot save players with too long names
### Steps to Reproduce and Observed Behavior

The file name can exceed the limits of the file system. We need some different way of uniquely identifying which file belongs to which player.

### LINKED ISSUE #1737: Authentication without a central authentication server
To my surprise it seems like this is actually possible

### Design Goals
- The client should be able to log in with a single password and username(or another identifier, to be decided) to all servers
- A malicious server must not be able to steal your credentials

### Registration
1. The client sends its username/id to the server
2. The server creates a new private/public key pair for the username/id and stores them in the player file.
3. The server sends the public key to the client
4. The client generates a new password for this particular server
5. The client stores its password alongside the server public key and encrypts them using the player's password
6. The client sends the encrypted password+public key back to the server
7. The server stores the encrypted password+public key in the player file
8. The client logs in using the method below

### Login
1. The client sends its username/id to the server
2. The server looks up the encrypted password+public key using the username/id and sends it to the client
3. The client decrypts the per-server password and public key using the player's private password
4. The client now encrypts the per-server password with the server's public key, note that only the real server can decrypt the password.
5. The server decrypts the password computes a hash and compares it with the stored hash, if no hash is stored yet (because we are in the registration process) it stores it now.

### Remaining problems
- The server knows the public, the per server password and knows the player-password encrypted version of these.
Together this may be enough to brute-force the player's password.
→ A sufficiently secure encrpytion algorithms needs to be used to prevent this.
- If a malicious server relays this handshake to a target server, then it can steal your account for a session there.
→ A solution could be to send the IP the client connected to alongside the per server password in step 4. This would allow the server to identify if the client directly connected to it or chose an indirect path.
- If the world is shared with other players, then the per player private keys would be public. This would allow a malicious server to decrypt your per-server password, allowing them to join the original server.
→ It would make sense to store the private key somewhere separate from the world itself to still allow world downloads. Furthermore a mechanism to re-register a player on the world copy is needed.
- Anyone could create a new account under your username/id on a server and you wouldn't be able to claim it back
→ I don't think this is even solvable. It would be rather annoying to the player if this happens, but they could just change their name in that case.

### Sources
I took some inspiration from http://www.peerson.net/papers/passwordsP2P.pdf

### LINKED ISSUE #1812: Display names
It would be nice if players could change their name without losing their inventory (and without having to rejoin the game).

Decoupling "account" name and in-game name would also be a first step towards #1737

### PR DESCRIPTION
**Pull request by IntegratedQuantum**
This will be a big and long PR, but it really is time to start working on it. So far I haven't done much.

Remaining work:
- [x] Validate and generate the seed phrases based on BIP39. (This makes it easy for a user to find errors when entering the seed string) Forward compatibility is ensured by allowing the user to bypass the checks by clicking the button a second time.
- [x] Decide on a public/private key algorithms
- [x] Create account page
- [x] How to seed the CSPRNG → using the one from the standard library which is seeded from the OS
- [x] Generate public/private key pair from seed phrase
- [x] Add option to store it on file and encrypt it (can we interact with outside solutions, e.g. the Linux keyring?)
- [x] Add TLS to handle all the encryption logic
- [x] Do the authentication network logic by signing the TLS initialization data on the client
- [x] Implement migration path for old usernames (from before this)
- [x] Implement migration path for compromised signature algorithms: The server asks for all signatures that were used in the past and then looks for the player based on their public keys in the various old algorithms
- [x] Change duplicate name joining prevention check to a duplicate player index check
- [x] Use `std.crypto.secureZero(comptime T: type, s: []T)` instead of `@memset`
- [x] ~~Figure out what to do about the certificate situation~~ → #2538
- [x] move mbed-TLS to Cubyz-libs
- [x] Deinit mbed-TLS data
- [x] logout button

fixes #1737
fixes #1736
fixes #1812

### CODE REVIEW

**Comment by IntegratedQuantum** [comment]
I think I'll use the [BIP39](https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki) (bitcoin) word list of 2048 words for the seed phrase. It has some useful properties, and has been carefully curated to avoid mistakes from similar sounding words and such.

File: src/network/authentication.zig [hunk 1]
```diff
@@ -0,0 +1,247 @@
...
+				result.appendAssumeCapacity(std.ascii.toLower(char));
+			} else if (std.ascii.isWhitespace(char)) {
+				if (result.items.len != 0 and result.items[result.items.len - 1] != ' ') {
+					result.appendAssumeCapacity(char);
+				}
+			} else {
+				failureText.print("Seed phrase contains invalid character '{c}', only ASCII letters and whitespaces are allowed\n", .{char});
+			}
+		}
+		if (result.items[result.items.len - 1] == ' ') _ = result.pop();
```
Comment (Wunka) [inline src/network/authentication.zig]: Do I understand that correctly that multiple and trailing whitespaces are ignored? 
Problem I had is that it didn't pop my (through bad coping) \n at the end and said as the error message: 
"The 15th word of the seed phrase is not a part of the wordlist"
`std.ascii.isWhitespcace` seems to allow `'\t'...'\r'`.
Also at the end you don't do the result.items.en != 0 check so the game crashes if an you press "apply" without having written anything
