### PR TITLE
Round up hp when displaying it

### LINKED ISSUE #2308: The player can appear to have 0 health yet not die
### Steps to Reproduce and Observed Behavior

Steps to Reproduce:
Take damage such that your health will be less than 0.5

Observed Behavior:
The health bar will appear empty, as though you somehow have 0 hp

### PR DESCRIPTION
**Pull request by H41ogen**
Fixes #2308.
The healthbar now displays the health rounded up, which prevents it from displaying as 0 when the player's health is above 0.

### CODE REVIEW

File: src/gui/windows/healthbar.zig [hunk 1]
```diff
@@ -52,9 +52,9 @@ pub fn render() void {
 			x = 0;
 			y += 20;
 		}
-		if(health + 1 <= main.game.Player.super.health) {
+		if(health + 0.5 < main.game.Player.super.health) {
 			heartTexture.bindTo(0);
-		} else if(health + 0.5 <= main.game.Player.super.health) {
+		} else if(health < main.game.Player.super.health) {
```
Comment (IntegratedQuantum) [inline src/gui/windows/healthbar.zig]: Honestly this whole construct is rather confusing. Would you mind cleaning it up a little while you are at it?

Ideally it should be separate loops, one for full hearts, one for empty hearts and one if for the half heart. With the number computed upfront.

Comment (H41ogen) [reply src/gui/windows/healthbar.zig]: making 3 separate loops resulted in a whole lot of duplicate code, so i decided to calculate the number of each heart type upfront and then loop through the total number of hearts.

File: src/gui/windows/healthbar.zig [hunk 2]
```diff
@@ -44,24 +44,32 @@ pub fn deinit() void {
 
 pub fn render() void {
 	draw.setColor(0xffffffff);
-	var y: f32 = 0;
+	const displayHealth = @max(0, main.game.Player.super.health);
+	const wholeHearts: usize = @intFromFloat(@ceil(displayHealth*2)/2);
+	const halfHeart: usize = if(0 < @mod(displayHealth, 1) and @mod(displayHealth, 1) < 0.5) 1 else 0;
```
Comment (IntegratedQuantum) [inline src/gui/windows/healthbar.zig]: I think it's a bit difficult to understand what's going on here.
I'd suggest to split this with a new variable:
```zig
const halfHeartUnits: usize = @intFromFloat(@ceil(displayHealth*2));
const wholeHearts = halfHeartUnits/2;
const halfHeart = halfHeartUnits%2;
```

File: src/gui/windows/healthbar.zig [hunk 3]
```diff
@@ -44,24 +44,33 @@ pub fn deinit() void {
...
+	const wholeHearts = halfHeartUnits/2;
+	const halfHeart = halfHeartUnits%2;
+	const totalHearts: usize = @intFromFloat(@ceil(main.game.Player.super.maxHealth));
+
 	var x: f32 = 0;
-	var health: f32 = 0;
-	while(health < main.game.Player.super.maxHealth) : (health += 1) {
+	var y: f32 = 0;
+	var i: usize = 0;
+	while(i < totalHearts) : (i += 1) {
```
Comment (IntegratedQuantum) [inline src/gui/windows/healthbar.zig]: Also you can use a normal for loop now:
```suggestion
	for(0..totalHearts) |i| {
```

**Review by IntegratedQuantum — CHANGES_REQUESTED** [review]

**Review by IntegratedQuantum — APPROVED** [review]
