### PR TITLE
Check if the biome exists before teleporting

### LINKED ISSUE #2606: Attempting to teleport to a biome that doesn't exist throws an error
### Steps to Reproduce and Observed Behavior

Ideally, this should just display the message that the biome is invalid, no?

Image

### PR DESCRIPTION
**Pull request by BoySanic**
This prevents a pop-up error when a  user teleports to a non-existent biome. Seemed excessive to give them a pop-up for what should just be user error.

Fixes #2606

### CODE REVIEW

File: src/server/command/tp.zig [hunk 1]
```diff
@@ -8,11 +8,11 @@ pub const usage = "/tp <x> <y>\n/tp <x> <y> <z>\n/tp <biome>";
 
 pub fn execute(args: []const u8, source: *User) void {
 	if (std.mem.containsAtLeast(u8, args, 1, ":")) {
-		const biome = main.server.terrain.biomes.getById(args);
```
Comment (IntegratedQuantum) [inline src/server/command/tp.zig:11]: I think it would be better to have a version that returns an optional.
A similar effort has also been started for the blocks getById, ideally all these functions should return optional and error handling should be done when needed at the callsite.

Comment (BoySanic) [reply src/server/command/tp.zig:11]: Done. This should be a little closer to what you wanted, though the PR is larger.

Comment (IntegratedQuantum) [reply src/server/command/tp.zig:11]: Please use `const biome = main.server.terrain.biomes.getByIdOptional(args) orelse {...error path...}` to avoid having excessive line changes, and to avoid this random else at the bottom of the block that no one can tell what it even belongs to.

**Review by IntegratedQuantum — CHANGES_REQUESTED** [review]
