### PR TITLE
Better notification when password is incorrect

### LINKED ISSUE #2750: Better notification when password is incorrect
"the game encountered errors", pointing at "AuthenticationFailed" in the logs is not particularly helpful for the average user.

### PR DESCRIPTION
**Pull request by H41ogen**
Fixes #2750

image

### CODE REVIEW

File: src/gui/windows/authentication/unlock.zig [hunk 1]
```diff
@@ -24,11 +24,20 @@ const padding: f32 = 8;
...
+var incorrectPassword = false;
+
 fn apply() void {
 	var failureText: main.List(u8) = .init(main.stackAllocator);
 	defer failureText.deinit();
 	const accountCode = main.settings.storedAccount.decryptFromPassword(textComponent.currentString.items, &failureText) catch |err| {
-		std.log.err("Encountered error while decrypting password: {s}", .{@errorName(err)});
+		if (err == error.AuthenticationFailed) {
+			incorrectPassword = true;
+			onClose();
```
Comment (IntegratedQuantum) [inline src/gui/windows/authentication/unlock.zig]: This is a data corruption, onClose will clean up the components, which are currently being iterated, as soon as the function returns, you are accessing invalid memory from e.g. the Button that called this function.

Instead store the label in a global and change only the label text.

**Comment by IntegratedQuantum** [comment]
also please link the issue this fixes.

File: src/gui/windows/authentication/unlock.zig (hunk 1 above)
Comment (H41ogen) [reply src/gui/windows/authentication/unlock.zig]: fixed

File: src/gui/windows/authentication/unlock.zig [hunk 2]
```diff
@@ -24,11 +24,17 @@ const padding: f32 = 8;
...
+
 fn apply() void {
 	var failureText: main.List(u8) = .init(main.stackAllocator);
 	defer failureText.deinit();
 	const accountCode = main.settings.storedAccount.decryptFromPassword(textComponent.currentString.items, &failureText) catch |err| {
-		std.log.err("Encountered error while decrypting password: {s}", .{@errorName(err)});
+		if (err == error.AuthenticationFailed) {
+			incorrectPasswordLabel.updateText("#ff0000Incorrect password.");
+		} else {
+			std.log.err("Encountered error while decrypting password: {s}", .{@errorName(err)});
```
Comment (IntegratedQuantum) [inline src/gui/windows/authentication/unlock.zig]: This means that the stored data got corrupted. Since we already have a label for this, I think we should print it onto it, something like this:
`"#ff0000Encrypted authentication data is corrupted: {s} Please login with your Account Code again.", .{@errorName(err)}`

**Comment by IntegratedQuantum** [comment]
please fix CI failure, you need to allocPrint the text before passing it to the label.

File: src/gui/windows/authentication/unlock.zig (hunk 2 above)
Comment (H41ogen) [reply src/gui/windows/authentication/unlock.zig]: This has the problem of now stretching across multiple lines

Comment (IntegratedQuantum) [reply src/gui/windows/authentication/unlock.zig]: Well, you could also add a helper function to the label that formats the input to a temporary.

**Review by IntegratedQuantum — APPROVED** [review]
I fixed the remaining issues due to the closeness of the release

**Comment by H41ogen** [comment]
That's fair, I have a lot on my plate right now so I wouldn't have gotten to this
