### PR TITLE
Store the block type + data as a string in blueprint palettes

### LINKED ISSUE #2477: Migrations don't work on ore data
### Steps to Reproduce and Observed Behavior

Ore rotation stores host block information in its data value. That information is not affected by migrations so blueprints which used such ore-block combination get broken.

Image

Related-to: #1930

### PR DESCRIPTION
**Pull request by IntegratedQuantum**
Instead of only storing the block type, the blueprint palette now also stores the data, e.g.:
```
Blueprint block palette:
palette[0]: cubyz:moss:cubyz:aerosoil
palette[1]: cubyz:aerosoil
palette[2]: cubyz:moss:cubyz:permafrost
Saved clipboard to blueprint file: test.blp
```

fixes #2477

@Argmaster I would like your review here, since you wrote the blueprint code, and since I think it would be rather annoying if anything breaks with this.

I tested this by loading and pasting some mossy aerosoil into an old world (which due to its age has aerosoil mapped to a different index).

### CODE REVIEW

File: src/blocks.zig [hunk 1]
```diff
@@ -292,12 +296,15 @@ fn parseBlockData(fullBlockId: []const u8, data: []const u8) ?u16 {
 	};
 }
 
-pub fn parseBlock(data: []const u8) Block {
+pub fn parseBlock(data: []const u8, comptime config: ParseBlockConfig) Block {
```
Comment (Argmaster) [inline src/blocks.zig]: Why do we need that extra argument? Now you had to edit every call to this function, what's the benefit? U use it once.
I think there is a naming pattern in zig standard library for having function with extra arguments and one without those arguments?

Comment (IntegratedQuantum) [reply src/blocks.zig]: I found `...WithOptions` in the allocator interface.

File: mods/cubyz/rotation/ore.zig [hunk 2]
```diff
@@ -72,3 +72,7 @@ pub fn onBlockBreaking(_: main.items.Item, _: Vec3f, _: Vec3f, currentData: *Blo
 	currentData.typ = currentData.data;
 	currentData.data = 0;
 }
+
+pub fn formatBlockData(block: Block, _list: *main.List(u8)) void {
```
Comment (Argmaster) [inline mods/cubyz/rotation/ore.zig:76]: I think this should be symmetrical in the end and it should follow `save`/`load` naming pattern (or is it `save` or `store`, we have some consistency issues here no?). For now just complying with the naming would be enough since we aren't loading anything really, `load` would be basically #2793

Comment (Argmaster) [reply mods/cubyz/rotation/ore.zig:76]: Hm, or is it more of a ` format`/`parse`?
I guess the name might be fine 🤷

Comment (IntegratedQuantum) [reply mods/cubyz/rotation/ore.zig:76]: Yeah, I intended this to be format/parse pair.
Though it is saved in the blueprint, it is (at least on the parsing addons side) also meant for human-readable stuff.
