### PR TITLE
Fix menu fov overriding fov setting

### LINKED ISSUE #1962: The FOV is reset to 70 in the game when changing it and setting it to anything else.
I think the problem is related to the background image which overwrites the FOV.
Reseting the matrix on join should fix it.

### PR DESCRIPTION
**Pull request by awwddf**
Fixes #1962 by adding a defer which sets the viewport fov to whatever the selected fov is in settings. This line is located right under the one which sets the fov to 70 while in the main menu. So upon entering a world from now on, the fov should properly be adjusted to whatever you chose.

I'm still pretty new to GitHub and this is my first pull request, so please let me know if there are any issues or if I can do anything better.

### CODE REVIEW

File: src/renderer.zig [hunk 1]
```diff
@@ -593,6 +593,7 @@ pub const MenuBackGround = struct {
 		const viewMatrix = Mat4f.rotationZ(angle);
 		pipeline.bind(null);
 		updateViewport(main.Window.width, main.Window.height, 70.0);
+		defer updateViewport(Window.width, Window.height, settings.fov);
```
Comment (IntegratedQuantum) [inline src/renderer.zig:596]: I just noticed that this (and the line above) are really inefficient, since it rebuilds the framebuffer.
Do you think you could also look into fixing this? If not we could also make an issue for it.

Comment (awwddf) [reply src/renderer.zig:596]: I could try to look into this. Still pretty new to Zig so it may take me a bit, might be a good idea to just create a new issue for it for now. But just so that I understand what you mean about the framebuffer stuff: the updateViewport function builds the framebuffer. So calling that function somewhere just once and passing on the correct fov argument is the ideal way, right?
