### PR TITLE
fix contorller issues

### LINKED ISSUE #1924: Can't Close Settings UI
### Steps to Reproduce and Observed Behavior

I'm using the Windows-x86_64 0.0.0 version, and I can't close the UI in the settings no matter what I click or press.

https://github.com/user-attachments/assets/41e87a23-d92b-4d2f-9244-3bfe38e78092

### LINKED ISSUE #1958: Controller and key board mouse
### Steps to Reproduce and Observed Behavior

Having a controller plugged in, and using mouse / keyboard to play make the cursor goes in the top right (with UV coordinate) by 1 pixel each frame.
I'm playing on ArchLinux / Hyprland, with prebuilt binary from the latest release at this time.
I'm playing with an AMD 9950x3D and a RTX 5070Ti.

### PR DESCRIPTION
**Pull request by RanPix**
fixes #1958
fixes #1924

### CODE REVIEW

**Comment by ikabod-kee** [comment]
For some reason, it set my deadzone to 301%

**Comment by ikabod-kee** [comment]
image
The slider isn't there so I can't change it back

**Comment by ikabod-kee** [comment]
I tried changing my settings via the settings file but it keeps reverting to 301%

**Comment by RanPix** [comment]
you sure you reset the settings in both debug settings file and normal settings file?

**Comment by IntegratedQuantum** [comment]
@RanPix since this likely affects other users from a previous version, could you please fix this in the slider, so it still displays the thing even if it's outside the range.

**Comment by RanPix** [comment]
done

**Comment by IntegratedQuantum** [comment]
@ikabod-kee please check if it works now

**Comment by ikabod-kee** [comment]
Sorry for the delay, was moving stuff!
This fixes the issues mentioned. 👍

File: src/graphics/Window.zig [hunk 1]
```diff
@@ -213,7 +232,7 @@ pub const Gamepad = struct {
 		}
 	};
 	pub fn downloadControllerMappings() void {
-		if(builtin.mode == .Debug) return; // TODO: The http fetch adds ~5 seconds to the compile time, so it's disabled in debug mode, see #24435
+		// if(builtin.mode == .Debug) return; // TODO: The http fetch adds ~5 seconds to the compile time, so it's disabled in debug mode, see #24435
```
Comment (IntegratedQuantum) [inline src/graphics/Window.zig]: revert this change please

**Review by IntegratedQuantum — CHANGES_REQUESTED** [review]

**Comment by RanPix** [comment]
done

**Review by IntegratedQuantum — APPROVED** [review]
