### PR TITLE
switch winsock2 errors

### LINKED ISSUE #2410: Game crashes when loading a singleplayer world while the multiplayer window is open
### Steps to Reproduce and Observed Behavior

1. Open the game
2. Click on 'Multiplayer'
3. Click on 'Singleplayer'
4. Click on a save

stack trace:

~\Cubyz\src\server\server.zig:351:3: 0x7ff6cd2015b1 in init (Cubyz_zcu.obj)
  @panic("Could not open Server.");
  ^
~\Cubyz\src\server\server.zig:486:6: 0x7ff6cd1c9974 in startFromExistingThread (Cubyz_zcu.obj)
 init(name, port);
     ^
~\Cubyz\src\server\server.zig:481:25: 0x7ff6cd4c67b1 in startFromNewThread (Cubyz_zcu.obj)
 startFromExistingThread(name, port);

### PR DESCRIPTION
**Pull request by Wunka**
With the PR I will go over the errors and lock if I find a suitable error from posix so we have a unified errorset.
Fixes #2410

### CODE REVIEW

**Comment by Wunka** [comment]
The rest I have either not found in the posix.zig and was not sure what to apply there are only used with unreachable or have different posix errors (sometimes unreachable)  when applied to different functions.

**Comment by Wunka** [comment]
Looked again and this time in the newest posix.zig. Now the rest are either not mentioned (first 3 which are not changed) or have always a unreachable in posix.zig (other two).

File: src/network.zig [hunk 1]
```diff
@@ -29,17 +29,17 @@ const Socket = struct {
...
-			ws2.WSAEADDRINUSE => return error.WSAEADDRINUSE,
-			ws2.WSAEADDRNOTAVAIL => return error.WSAEADDRNOTAVAIL,
-			ws2.WSAEINVAL => return error.WSAEINVAL,
-			ws2.WSAENOBUFS => return error.WSAENOBUFS,
-			ws2.WSAENOTSOCK => return error.WSAENOTSOCK,
+			ws2.WSAENETDOWN => return error.NetworkDown,
+			ws2.WSAEACCES => return error.AccessDenied,
+			ws2.WSAEADDRINUSE => return error.AddressInUse,
+			ws2.WSAEADDRNOTAVAIL => return error.AddressNotAvailable,
+			ws2.WSAEINVAL => return error.SocketNotBound,
```
Comment (IntegratedQuantum) [inline src/network.zig]: This is not quite right, there are other ways that WSAEINVAL can happen besides not bound.

File: src/network.zig [hunk 2]
```diff
@@ -29,17 +29,17 @@ const Socket = struct {
 		switch(err) {
 			ws2.WSASYSNOTREADY => return error.WSASYSNOTREADY,
 			ws2.WSAVERNOTSUPPORTED => return error.WSAVERNOTSUPPORTED,
-			ws2.WSAEINPROGRESS => return error.WSAEINPROGRESS,
+			ws2.WSAEINPROGRESS => return error.BlockingOperationInProgress,
 			ws2.WSAEPROCLIM => return error.WSAEPROCLIM,
 			ws2.WSAEFAULT => return error.WSAEFAULT,
 			ws2.WSANOTINITIALISED => return error.WSANOTINITIALISED,
```
Comment (IntegratedQuantum) [inline src/network.zig]: Here we can put unreachable, since we do always call WSAStartup first.

File: src/network.zig [hunk 3]
```diff
@@ -29,17 +29,17 @@ const Socket = struct {
 		switch(err) {
 			ws2.WSASYSNOTREADY => return error.WSASYSNOTREADY,
 			ws2.WSAVERNOTSUPPORTED => return error.WSAVERNOTSUPPORTED,
-			ws2.WSAEINPROGRESS => return error.WSAEINPROGRESS,
+			ws2.WSAEINPROGRESS => return error.BlockingOperationInProgress,
 			ws2.WSAEPROCLIM => return error.WSAEPROCLIM,
 			ws2.WSAEFAULT => return error.WSAEFAULT,
```
Comment (IntegratedQuantum) [inline src/network.zig]: This can also be unreachable, since it only indicates that we passed a bad address which is a bug.

**Review by IntegratedQuantum — CHANGES_REQUESTED** [review]
For the first three, you can look in an older version of posix.zig, which still had the WSAStartup function in posix.zig (or os.zig), which is the only function that produces these errors.

File: src/network.zig (hunk 1 above)
Comment (Wunka) [reply src/network.zig]: from what I see there are (for us) 2 ways WSAEINVAL can happen when we bind (Alreadybound) and when we recfrrom (SocketNotBound) as I think the second one should not happen (if done corecctly) I have no changed it to AlreadyBound.

**Comment by Wunka** [comment]
have set the two to unreachable and found errors in os.zig for the other ones. (1. has in 0.15.1 SystemNotAvailable but I found the NetworkDown from master better.

File: src/network.zig (hunk 1 above)
Comment (IntegratedQuantum) [reply src/network.zig]: both cases seem like they should not happen. I think it would be better to put a `unreachable` there instead.

Comment (IntegratedQuantum) [reply src/network.zig]: in general, supplying an invalid argument usually is a programmer error and deserves a hard crash (in safe modes)

Comment (Wunka) [reply src/network.zig]: is now unreachable

**Review by IntegratedQuantum — APPROVED** [review]
