### PR TITLE
Fix menu background fov update inefficiency

### LINKED ISSUE #2001: The menu background rendering recreates the game's frame buffer twice per frame
extracted from https://github.com/PixelGuys/Cubyz/pull/1976#discussion_r2427322898

I think we should turn this into two separate functions. Changing the FOV should not trigger a framebuffer update.

### PR DESCRIPTION
**Pull request by BoySanic**
Fixes #2001

Added updateFov function
Removed fov argument from updateViewPort

### CODE REVIEW

File: src/renderer.zig [hunk 1]
```diff
@@ -129,11 +129,16 @@ var worldFrameBuffer: graphics.FrameBuffer = undefined;
 pub var lastWidth: u31 = 0;
 pub var lastHeight: u31 = 0;
 var lastFov: f32 = 0;
-pub fn updateViewport(width: u31, height: u31, fov: f32) void {
+
+pub fn updateFov(width: u31, height: u31, fov: f32) void {
 	lastWidth = @intFromFloat(@as(f32, @floatFromInt(width))*main.settings.resolutionScale);
 	lastHeight = @intFromFloat(@as(f32, @floatFromInt(height))*main.settings.resolutionScale);
```
Comment (IntegratedQuantum) [inline src/renderer.zig]: It shouldn't set this here.

File: src/graphics/Window.zig [hunk 2]
```diff
@@ -496,7 +496,7 @@ pub const GLFWCallbacks = struct { // MARK: GLFWCallbacks
 		std.log.info("Framebuffer: {}, {}", .{newWidth, newHeight});
 		width = @intCast(newWidth);
 		height = @intCast(newHeight);
-		main.renderer.updateViewport(width, height, main.settings.fov);
+		main.renderer.updateViewport(width, height);
```
Comment (IntegratedQuantum) [inline src/graphics/Window.zig:512]: Must also call updateFov, since the screen ratio may change

File: src/renderer.zig [hunk 3]
```diff
@@ -472,7 +477,6 @@ pub const MenuBackGround = struct {
 		viewMatrix: c_int,
 		projectionMatrix: c_int,
 	} = undefined;
-
```
Comment (IntegratedQuantum) [inline src/renderer.zig:475]: Please don't remove lines for no reason

File: src/renderer.zig [hunk 4]
```diff
@@ -592,12 +596,11 @@ pub const MenuBackGround = struct {
 		lastTime = newTime;
 		const viewMatrix = Mat4f.rotationZ(angle);
 		pipeline.bind(null);
-		updateViewport(main.Window.width, main.Window.height, 70.0);
```
Comment (IntegratedQuantum) [inline src/renderer.zig:595]: The background image should always be displayed at fov 70.

File: src/renderer.zig [hunk 5]
```diff
@@ -613,9 +616,9 @@ pub const MenuBackGround = struct {
 
 		const oldResolutionScale = main.settings.resolutionScale;
 		main.settings.resolutionScale = 1;
-		updateViewport(size, size, 90.0);
+		updateViewport(size, size);
```
Comment (IntegratedQuantum) [inline src/renderer.zig:614]: The background image must be recorded at fov 90

**Comment by BoySanic** [comment]
I changed my approach a little @IntegratedQuantum 

I now update fov to 70.0 only if the lastFov was not 70.0 in the MenuBackground.render() function. This should ideally only run once.

The defer is setting it back to main.settings.fov.

The secondary issue I had was that it would still allow you to update the fov via the settings and affect the menu. So I changed the setting in the graphics window so it only changes the setting.

The renderWorld function will run updateFov if lastFov != main.settings.fov which will happen when you change fov.
But the MenuBackground.render() function won't do this, it keeps the fov locked at 70 while the setting is allowed to change independently for when the game is  no longer on the menu.

File: src/renderer.zig [hunk 6]
```diff
@@ -297,6 +300,9 @@ pub fn renderWorld(world: *World, ambientLight: Vec3f, skyColor: Vec3f, playerPo
 	worldFrameBuffer.bindDepthTexture(c.GL_TEXTURE4);
 	worldFrameBuffer.unbind();
 	deferredRenderPassPipeline.bind(null);
+	if(lastFov != main.settings.fov) {
```
Comment (IntegratedQuantum) [inline src/renderer.zig]: This won't work when recording a background screenshot. Please test all features you changed before re-requesting my review.

**Comment by BoySanic** [comment]
Tested:

1. Taking background image (it saved the image, it shows the image on the title screen, and fov appears unchanged to the user when taking the image)
2. Changing fov in main menu (no apparent change to the user, but once they load into a world, it will have applied that change from main.settings.fov)
3. Changing fov while in a world (the fov appears to change instantaneously)

File: src/graphics/Window.zig [hunk 7]
```diff
@@ -509,7 +509,8 @@ pub const GLFWCallbacks = struct { // MARK: GLFWCallbacks
...
+		main.renderer.updateFov(main.settings.fov);
```
Comment (IntegratedQuantum) [inline src/graphics/Window.zig]: Don't need this here if you update it every frame anyways.

File: src/renderer.zig [hunk 8]
```diff
@@ -592,9 +598,9 @@ pub const MenuBackGround = struct {
 		lastTime = newTime;
 		const viewMatrix = Mat4f.rotationZ(angle);
 		pipeline.bind(null);
-		updateViewport(main.Window.width, main.Window.height, 70.0);
-		defer updateViewport(Window.width, Window.height, settings.fov);
-
+		if(lastFov != 70.0) {
```
Comment (IntegratedQuantum) [inline src/renderer.zig]: I think it would make sense to put the `lastFov != xxx` check into the function.

**Review by IntegratedQuantum — CHANGES_REQUESTED** [review]

File: src/renderer.zig (hunk 8 above)
Comment (BoySanic) [reply src/renderer.zig]: Done

Comment (BoySanic) [reply src/renderer.zig]: Something I don't love about this approach is that I'm setting a bool for special behavior in the renderWorld function if we're in the middle of taking a background image.

An idea I had to potentially fix this would be to have a `desiredFov` variable.

in `takeBackgroundImage` we set `desiredFov` to 90.0, defer setting it back to `main.settings.fov`
In the renderWorld function we run `updateFov(desiredFov)`

`desiredFov` defaults to `main.settings.fov` and is updated to `70.0` with a defer to update it back to `main.settings.fov` for the main menu

Comment (BoySanic) [reply src/renderer.zig]: That wouldn't work for the main menu, actually, but it would work for `takeBackgroundImage`, but it still uses an extra variable. So might as well keep the bool I guess.

Comment (IntegratedQuantum) [reply src/renderer.zig]: How about just moving the updateFov call further outside so that it doesn't fall into the scope of the takeBackgroundImage function anymore?

Comment (BoySanic) [reply src/renderer.zig]: I moved the updateFov calls into main (for main menu and when loaded into a world)

The last piece I don't entirely like is that I'm now checking if game.world is not null twice per frame effectively (once for the branch to updateFov in main, once in the render function to determine whether we're rendering the world or the menu background) and I don't see a great way to avoid that since takeBackgroundImage also needs that `game.world` for `world.ambientLight` and `renderWorld` in the render function.

Comment (BoySanic) [reply src/renderer.zig]: I have 2 approach ideas:

1. Live with checking this twice per frame
2. Get rid of `renderer.render` and directly call `MenuBackground.render` and `renderer.renderWorld` from main. Call renderWorld from takeBackgroundImage with the same `if(game.world) |world|` check. Checking this in two places may not be the worst since takeBackgroundImage should only run when you press the screenshot key, not every frame.

File: src/main.zig [hunk 9]
```diff
@@ -638,6 +638,11 @@ pub fn main() void { // MARK: main()
 		}
 
 		if(!isHidden) {
+			if(game.world) |_| {
```
Comment (IntegratedQuantum) [inline src/main.zig]:
```suggestion
			if(game.world != null) {
```

Comment (BoySanic) [reply src/main.zig]: Done

File: src/renderer.zig (hunk 8 above)
Comment (IntegratedQuantum) [reply src/renderer.zig]: The whole takeBackgroundImage should only be run when in the game, so it might make sense to change functions to fit that.

Comment (BoySanic) [reply src/renderer.zig]: I've changed the function.

I added a `std.debug.assert` to `renderer.render` too. If I misunderstand how to use that, let me know. But my intention was to prevent people from running that function if game.world is null (and the assert should prevent us from making changes that don't obey this)

Comment (IntegratedQuantum) [reply src/renderer.zig]: Yes, assert is good there.
