### PR TITLE
Press C to open creative inventory without toggling menu first

### LINKED ISSUE #401: Pressing `C` while the inventory is open no longer opens the creative inventory, instead it closes the gui.
It seems that this was broken by in #382 by changing
```diff
---	ungrabMouse();
+++	gui.toggleGameMenu();
```

@tillpp it would be great if you could comment on what you wanted to accomplish with it so we can try to satisfy both our use cases.

### PR DESCRIPTION
**Pull request by BoySanic**
Fixes #401 
There could be a simpler way to achieve this, but for now to avoid having to set a bool every time this specific window closes, it loops when you press the `openCreativeInventory` keybind over the open windows and if the id matches, it sets the bool to true.

Then if the window is opened, it will toggle the menu without opening the window.
If the window is not opened, it will open the window but only toggle the menu if the mouse is currently grabbed (and hud would be hidden in that case)

### CODE REVIEW

**Review by IntegratedQuantum — CHANGES_REQUESTED** [review]
This is a complicated solution for a simple problem.

I think it would make sense to fundamentally rethink the behavior of the creative inventory here.

**Comment by BoySanic** [comment]
This should be much simpler, and it seems to exhibit mostly the same behavior except that `C` doesn't close the hud anymore. Only opens it. You'd still have to press Esc to close the hud. 

Not the end of the world imo

File: src/main.zig [hunk 1]
```diff
@@ -294,7 +294,10 @@ fn openInventory(_: Window.Key.Modifiers) void {
 fn openCreativeInventory(_: Window.Key.Modifiers) void {
 	if(game.world == null) return;
 	if(!game.Player.isCreative()) return;
-	gui.toggleGameMenu();
+
+	if(Window.grabbed) {
+		gui.toggleGameMenu();
+	}
```
Comment (IntegratedQuantum) [inline src/main.zig]: There is a helper function for this: `ungrabMouse`

Comment (BoySanic) [reply src/main.zig]: image
Is there a purpose for the parameter if it's unused anyway?

Comment (IntegratedQuantum) [reply src/main.zig]: It is needed for the callback.

Comment (BoySanic) [reply src/main.zig]: Should be fixed now.

**Comment by BoySanic** [comment]
RIP CI on this one

**Comment by IntegratedQuantum** [comment]
restarted CI, it now has compiler errors.

**Comment by BoySanic** [comment]
Strange! It compiled on my system.

I can see what I can do.

**Comment by BoySanic** [comment]
Fixed :+1:

File: src/main.zig [hunk 2]
```diff
@@ -283,10 +283,11 @@ fn ungrabMouse(_: Window.Key.Modifiers) void {
 		gui.toggleGameMenu();
 	}
 }
-fn openCreativeInventory(_: Window.Key.Modifiers) void {
```
Comment (IntegratedQuantum) [inline src/main.zig:286]: Could you explain why you added a line here, when there is no line between functions in the entire rest of the callback block?

Comment (BoySanic) [reply src/main.zig:286]: I think it was an artifact from merging. Wasn't intentional.
