### PR TITLE
Stop panic when blueprint doesn't exist for biome

### LINKED ISSUE #1898: The game crashes when a blueprint is not found
The game must not crash on user errors.

```
thread 40834 panic: Could not find structure building block with id 'my_addon:tree/stem'
/home/mint/Cubyz/src/utils.zig:2286:2: 0x159d40d in panicWithMessage__anon_112850 (Cubyz)
 @panic(message);
 ^
/home/mint/Cubyz/src/server/terrain/simple_structures/SbbGen.zig:34:30: 0x1451bca in loadModel (Cubyz)
  main.utils.panicWithMessage("Could not find structure building block with id '{s}'", .{structureId});
                             ^
/home/mint/Cubyz/src/server/terrain/biomes.zig:43:28: 0x145d299 in init (Cubyz)
   .data = vtable.loadModel(arenaAllocator.allocator(), parameters),
                           ^
/home/mint/Cubyz/src/server/terrain/biomes.zig:689:12: 0x13e15e4 in registerBiome (Cubyz)
 biome.init(id, paletteId, zon);
           ^
/home/mint/Cubyz/src/assets.zig:621:16: 0x13dd600 in loadWorldAssets (Cubyz)
  registerBiome(nextBiomeNumericId, entry.key_ptr.*, entry.value_ptr.*);
               ^
/home/mint/Cubyz/src/server/world.zig:533:34: 0x14b63d4 in init (Cubyz)
  try main.assets.loadWorldAssets(try std.fmt.allocPrint(arena.allocator, "{s}/saves/{s}/assets/", .{files.cubyzDirStr(), path}), self.blockPalette, self.itemPalette, self.toolPalette, self.biomePalette);
                                 ^
/home/mint/Cubyz/src/server/server.zig:320:26: 0x146a534 in start (Cubyz)
 world = ServerWorld.init(name, null) catch |err| {
                         ^
/home/mint/Cubyz/compiler/zig/lib/std/Thread.zig:510:13: 0x13f49cb in entryFn (Cubyz)
            @call(.auto, f, args);
            ^
./nptl/pthread_create.c:442:8: 0x7afc0c894ac2 in start_thread (pthread_create.c)
../sysdeps/unix/sysv/linux/x86_64/clone3.S:81:0: 0x7afc0c92684f in ??? (../sysdeps/unix/sysv/linux/x86_64/clone3.S)
???:?:?: 0x0 in ??? (???)
Aborted (core dumped)
```

### LINKED ISSUE #1932: [SBB] SegFault during SBB validation of invalid config
### Steps to Reproduce and Observed Behavior

```
Segmentation fault at address 0xffffffffffffffff
C:\Users\argma\dev\Cubyz5\src\server\terrain\structure_building_blocks.zig:318:30: 0x7ff661c391c9 in postResolutionChecks (Cubyz_zcu.obj)
  for(self.blueprints.items, 0..) |blueprints, blueprintIndex| {
                             ^
C:\Users\argma\dev\Cubyz5\src\server\terrain\structure_building_blocks.zig:379:57: 0x7ff661c38dab in registerSBB (Cubyz_zcu.obj)
 for(structureList.items) |sbb| sbb.postResolutionChecks();
                                                        ^
C:\Users\argma\dev\Cubyz5\src\assets.zig:605:21: 0x7ff661c3a8a9 in loadWorldAssets (Cubyz_zcu.obj)
 try sbb.registerSBB(&worldAssets.structureBuildingBlocks);
                    ^
C:\Users\argma\dev\Cubyz5\src\server\world.zig:533:34: 0x7ff661e7d7b0 in init (Cubyz_zcu.obj)
  try main.assets.loadWorldAssets(try std.fmt.allocPrint(arena.allocator, "{s}/saves/{s}/assets/", .{files.cubyzDirStr(), path}), self.blockPalette, self.itemPalette, self.toolPalette, self.biomePalette);
                                 ^
C:\Users\argma\dev\Cubyz5\src\server\server.zig:320:26: 0x7ff661e15330 in init (Cubyz_zcu.obj)
 world = ServerWorld.init(name, null) catch |err| {
                         ^
C:\Users\argma\dev\Cubyz5\src\server\server.zig:445:6: 0x7ff661d8e66f in start (Cubyz_zcu.obj)
 init(name, port);
     ^
C:\Users\argma\dev\Cubyz5\compiler\zig\lib\std\Thread.zig:510:13: 0x7ff661cf6a84 in callFn__anon_91057 (Cubyz_zcu.obj)
            @call(.auto, f, args);
            ^
C:\Users\argma\dev\Cubyz5\compiler\zig\lib\std\Thread.zig:623:30: 0x7ff661c5a6b4 in entryFn (Cubyz_zcu.obj)
                return callFn(f, self.fn_args);
                             ^
???:?:?: 0x7ffb66dae8d6 in ??? (KERNEL32.DLL)
???:?:?: 0x7ffb67b68d9b in ??? (ntdll.dll)
```

Seems to be caused by use of non-existent blueprints in configuration or sth like this. Discovered while working on #1930 with this invalid config:

```
.{
	.blueprints = .{
		.{.id = "cubyz:tree/mahogany/sapele/medium/stem/0"},
		.{.id = "cubyz:tree/mahogany/sapele/medium/stem/1"},
		.{.id = "cubyz:tree/mahogany/sapele/medium/full/0"},
		.{.id = "cubyz:tree/mahogany/sapele/medium/full/1"},
	},
	.children = .{
		.red = "cubyz:tree/mahogany/sapele/medium/branch/red",
		.green = "cubyz:tree/mahogany/sapele/medium/branch/green",
		.blue = "cubyz:tree/mahogany/sapele/medium/branch/blue",
		.white = "cubyz:tree/mahogany/sapele/medium/top",
		.yellow = "cubyz:tree/mahogany/deco",
	},
}

```

Config is invalid because none of blueprints mentioned exist.

SegFault while validating invalid SBB configuration is not an acceptable outcome, it should print a user friendly message instead.

[latest.log](https://github.com/user-attachments/files/22788493/latest.log)

### PR DESCRIPTION
**Pull request by BoySanic**
I just have it returning null if it can't find the blueprint and printing an error in the log.
It should work the same as if the id was not found.
Fixes #1898
Fixes #1932

### CODE REVIEW

File: src/server/terrain/biomes.zig [hunk 1]
```diff
@@ -34,13 +34,18 @@ pub const SimpleStructureModel = struct { // MARK: SimpleStructureModel
 
 	pub fn initModel(parameters: ZonElement) ?SimpleStructureModel {
 		const id = parameters.get([]const u8, "id", "");
+		const structure = parameters.get([]const u8, "structure", "");
 		const vtable = modelRegistry.get(id) orelse {
 			std.log.err("Couldn't find structure model with id {s}", .{id});
 			return null;
 		};
+		const vtableModel = vtable.loadModel(parameters) orelse {
+			std.log.err("Couldn't find blueprint with id '{s}'. Dropping model from biome.", .{structure});
```
Comment (Argmaster) [inline src/server/terrain/biomes.zig]: SBBs are just one of many structure types and the list will be extended in the future, so this error message cannot directly reference `structure` field. Instead this message probably would be better fitted in SBB code and here a more generic one would be appropriate and here a more generic message should be logged.

File: src/server/terrain/biomes.zig [hunk 2]
```diff
@@ -20,7 +20,7 @@ pub const SimpleStructureModel = struct { // MARK: SimpleStructureModel
 		water_surface,
 	};
 	const VTable = struct {
-		loadModel: *const fn(parameters: ZonElement) *anyopaque,
+		loadModel: *const fn(parameters: ZonElement) ?*anyopaque,
```
Comment (Argmaster) [inline src/server/terrain/biomes.zig:23]: Although compiler seems to ignore it, I think it is unsafe to use `?*anyopaque` here without changing the return type in all structure implementation. Current implementation can support it, but its definitely not the part of the contract. Even if it would be completely safe, for sake of consistency return type in every implementation of `loadModel` should be optional.

File: src/server/terrain/biomes.zig (hunk 1 above)
Comment (BoySanic) [reply src/server/terrain/biomes.zig]: Understood. Thanks! I'll update that

File: src/server/terrain/biomes.zig (hunk 2 above)
Comment (BoySanic) [reply src/server/terrain/biomes.zig:23]: Updated

File: src/server/terrain/simple_structures/SbbGen.zig [hunk 3]
```diff
@@ -26,12 +26,13 @@ pub fn getHash(self: SbbGen) u64 {
 	return std.hash.Wyhash.hash(@intFromEnum(self.placeMode), self.structureRef.id);
 }
 
-pub fn loadModel(parameters: ZonElement) *SbbGen {
+pub fn loadModel(parameters: ZonElement) ?*SbbGen {
 	const structureId = parameters.get(?[]const u8, "structure", null) orelse {
 		main.utils.panicWithMessage("Error loading generator 'cubyz:sbb' structure field is mandatory.", .{});
```
Comment (IntegratedQuantum) [inline src/server/terrain/simple_structures/SbbGen.zig]: Please also fix this while you are at it.

File: src/server/terrain/biomes.zig [hunk 4]
```diff
@@ -38,9 +38,13 @@ pub const SimpleStructureModel = struct { // MARK: SimpleStructureModel
 			std.log.err("Couldn't find structure model with id {s}", .{id});
 			return null;
 		};
+		const vtableModel = vtable.loadModel(parameters) orelse {
+			std.log.err("Internal error occurred attempting to load structure with id {s} Dropping model from biome.", .{id});
```
Comment (IntegratedQuantum) [inline src/server/terrain/biomes.zig]: It's not an internal error, instead it's (hopefully) an error that got nicely printed in the lines before.
```suggestion
			std.log.err("Error occurred while loading structure with id '{s}'. Dropping model from biome.", .{id});
```

Comment (BoySanic) [reply src/server/terrain/biomes.zig]: Done

File: src/server/terrain/simple_structures/SbbGen.zig (hunk 3 above)
Comment (BoySanic) [reply src/server/terrain/simple_structures/SbbGen.zig]: Done, this should now fix #1932 too.
I think my implementation might be a little ugly but I can clean that up later.

The root cause of the issue is that we resize `structureList` to a size larger than it would be if some sbbs are discarded.

Then when we loop over it, the last `n` items of the slice are invalid memory. (address aaaaaaaaa... and so on)

My fix is to bound the slice we loop over by how many items made it through registration. (`0..stage1Count`) Naming can be adjusted.

Comment (BoySanic) [reply src/server/terrain/simple_structures/SbbGen.zig]: I was thinking about this some more, and an ideal approach would resize the list to the new size.

I couldn't think of a good way to do this, the typical resize function doesn't allow you to make the list smaller.

I guess we could supply a new, smaller list with the `0..stage1Count` slice to reassign to `structureList`? Unless there's some obvious way I'm missing to reduce list size

File: src/server/terrain/structure_building_blocks.zig [hunk 5]
```diff
@@ -341,28 +340,27 @@ pub const StructureBuildingBlock = struct {
 pub fn registerSBB(structures: *Assets.ZonHashMap) !void {
 	std.debug.assert(structureList.items.len == 0);
 	std.debug.assert(structureMap.capacity() == 0);
-
 	structureList.resize(main.worldArena, structures.count());
 	structureMap.ensureTotalCapacity(main.worldArena.allocator, structures.count()) catch unreachable;
 
 	childrenToResolve = .init(main.stackAllocator);
 	defer childrenToResolve.deinit();
+	var stage1Count: u32 = 0;
```
Comment (Argmaster) [inline src/server/terrain/structure_building_blocks.zig]: Is stage1 count dangerous? Does it develop into stage2 count?
Sorry, but what's up with that name?

Comment (BoySanic) [reply src/server/terrain/structure_building_blocks.zig]: Lol

The name was because I was experimenting with trying to make the `structureList` smaller in stages.

The 1st stage was the initial stage that's the root cause of the problem
The 2nd stage was filtering via the `postResolutionChecks` function, which I ultimately didn't need to do to eliminate the root cause.

I can rename it to something more apparent

File: src/server/terrain/simple_structures/SbbGen.zig (hunk 3 above)
Comment (Argmaster) [reply src/server/terrain/simple_structures/SbbGen.zig]: Please read https://github.com/PixelGuys/Cubyz/blob/64b5813cab66d4a759a4c6c537d889edca013045/src/utils/list.zig#L15

Whole implementation
You will find solution to your problem there. A pretty one.

Comment (Argmaster) [reply src/server/terrain/simple_structures/SbbGen.zig]: Just so it's clear, none cares if we use the whole allocation or if we waste few entries of memory, only correctness matter.
If solution doesn't occur to you after reading List implementation I will gladly suggest a stage1Couny-free solution without further riddles.

File: src/server/terrain/structure_building_blocks.zig [hunk 6]
```diff
@@ -311,7 +311,6 @@ pub const StructureBuildingBlock = struct {
 		// Collect all unique child blocks used in blueprints of this SBB.
 		var childBlocksInBlueprints: ListUnmanaged(LocalBlockIndex) = .{};
 		defer childBlocksInBlueprints.deinit(main.stackAllocator);
-
```
Comment (Argmaster) [inline src/server/terrain/structure_building_blocks.zig:314]: Hey! That line was here for a purpose!
It separates lifetime management of variable from the algorithm!

File: src/server/terrain/simple_structures/SbbGen.zig (hunk 3 above)
Comment (BoySanic) [reply src/server/terrain/simple_structures/SbbGen.zig]: I refactored with .append, that seems better.

There's still a piece that needs the `loadedCount` but we're no longer directly assigning to the internal `.items` this way and can dynamically add size only when it's needed.

File: src/server/terrain/structure_building_blocks.zig (hunk 6 above)
Comment (BoySanic) [reply src/server/terrain/structure_building_blocks.zig:314]: I put it back :p

File: src/server/terrain/simple_structures/SbbGen.zig (hunk 3 above)
Comment (Argmaster) [reply src/server/terrain/simple_structures/SbbGen.zig]: Great! You almost nailed it. Now loadedCount should be just index.
Additionally you have to add ensureCapacity call so you guarantee that your list doesn't use 2N storage due to resizes, if someone allocate something else in meantime.

Comment (BoySanic) [reply src/server/terrain/simple_structures/SbbGen.zig]: Wouldn't `.append` end up calling `ensureCapacity`?

Comment (BoySanic) [reply src/server/terrain/simple_structures/SbbGen.zig]: > so you guarantee that your list doesn't use 2N storage due to resizes, if someone allocate something else in meantime

I'm not following. It'll only add capacity to the list when it adds a sbb during world load, which is discarded by the `worldArena` once the world closes. Where's `2N` coming from here?

Comment (Argmaster) [reply src/server/terrain/simple_structures/SbbGen.zig]: Yes, it will do that effectively log(N) times, allocating bigger region every time.
Depending on arena implementation, this will either just pollute the arena with unused allocations, or it will do that when those allocations are interleaved with different allocations, effectively resulting in doubled memory usage (well, how much memory you waste depend on the implementation - how big is the capacity overshoot on reallocation)
This is completely unnecessary because 99% you know exactly how many entries you need and in other cases you will need less than your original estimate.

Comment (BoySanic) [reply src/server/terrain/simple_structures/SbbGen.zig]: > this will either just pollute the arena with unused allocations

Why would it? If it did that, my implementation would not have fixed the issue.

The current implementation in master leaves unused allocations, which the loop for `postResolutionChecks` attempts to use, which is invalid because that memory was allocated but never assigned.

> This is completely unnecessary because 99% you know exactly how many entries you need 

Except we don't. We can hope every sbb is valid and resize the list to the count of sbbs, but until we finish trying to add them via `initFromZon` we won't know the final count. And if we just assume it's going to be that size we're back at the same problem we have in `master` right now where we loop over invalid memory that never gets used.

Then we need to either use a slice subset of the list to loop `postResolutionChecks` or we need to have a stack allocated temporary list for the initial load and use a slice from that to populate `structureList`.

Comment (BoySanic) [reply src/server/terrain/simple_structures/SbbGen.zig]: To be clear, it does not seem to add capacity to the list if we hit the `catch` on `initFromZon`. It cannot call the function to add capacity until the parameter is resolved.

Comment (Argmaster) [reply src/server/terrain/simple_structures/SbbGen.zig]: Yes, there is a bug in current implementation, at least after reviewing the code on phone I think I see it. Uninitialized objects should have been removed.

> > so you guarantee that your list doesn't use 2N storage due to resizes, if someone allocate something else in meantime
> 
> I'm not following. It'll only add capacity to the list when it adds a sbb during world load, which is discarded by the `worldArena` once the world closes. Where's `2N` coming from here?

Exactly here. World arena exists throughout whole gameplay, as long as the world is open. Therefore you will keep those unused allocations for most of the runtime. When you start appending, a list will start with small size, eg. N/8, then after reaching it's capacity (mind, not size, capacity!) it will reallocate (not resize!) to N/4 and repeat the cycle until it reaches N + possibly some overshoot due to X2 growth. Under certain circumstances allocation will not be resized (ie. won't be extended without changing address) but will be changed to completely different place, hence leaking the memory until world arena is reset.

Again, there is a difference between size and capacity, allocation size and array size.

Comment (BoySanic) [reply src/server/terrain/simple_structures/SbbGen.zig]: > Therefore you will keep those unused allocations for most of the runtime.

But my implementation avoids the unused allocations altogether?

It won't run `.append` if `.initFromZon` throws an error. It resolves the parameters before it ever calls the function.

Comment (BoySanic) [reply src/server/terrain/simple_structures/SbbGen.zig]: Measured via the `arenaAllocator.queryCapacity` function:
My branch: 

worldArena capacity before sbbs: 2950248 (usize)
worldArena capacity after sbbs: 2950248 (usize)

master:
worldArena capacity before sbbs: 2950492 (usize)
worldArena capacity after sbbs: 2950492 (usize)

Comment (Argmaster) [reply src/server/terrain/simple_structures/SbbGen.zig]: Ok, remove line with preallocation of hashmap memory and try checking size of the arena again.

```
structureMap.ensureTotalCapacity(main.worldArena.allocator, structures.count()) catch unreachable;
```

I am not sure it will expose the problem, because I am not sure what queryCapacity actually returns, but maybe it will be visible. 

Regardless of the outcome, it's not about current state of implementation, is about the semantics and potential future bugs.
When you call append on a list, it doesn't change it's allocation size by exactly one. It allocates continuous array of capacity of X elements but exposes size of 1. Then, you can freely append to it without reallocating until you try to append `X+1` element. Then, list requests a resize (reallocation) of it's allocation to `2*X` size. Allocator can decide to either grow that allocation, if it has unused space behind it, or has to create new memory region, copy old allocation into it and return a new pointer. Regardless of the path, list will expose size of `X+1`, but will have capacity of `2*X`. This will be repeated until list can contain all N elements. In case of Arena allocator, second reallocation path will result in old allocation being unused, but still owned by the arena.

File: src/server/terrain/biomes.zig (hunk 2 above)
Comment (IntegratedQuantum) [reply src/server/terrain/biomes.zig:23]: Could you then please also adjust the corresponding casting functions (utils.castFunctionReturnToAnyopaque and utils.castFunctionSelfToAnyopaque) so they do throw a compiler error on optional mismatch.

Comment (BoySanic) [reply src/server/terrain/biomes.zig:23]: I'm not entirely sure what you mean by optional mismatch, but I'll give it my best shot.

Comment (BoySanic) [reply src/server/terrain/biomes.zig:23]: I think I'm piecing it together.

You want a compiler error thrown if something is added that implements `loadModel` but it tries to return a non-optional `anyopaque`

Comment (BoySanic) [reply src/server/terrain/biomes.zig:23]: On second thought there's more nuance to that.
It needs to know whether to expect an optional anyopaque or just an anyopaque. I'm not sure how it can know that, yet.

Comment (BoySanic) [reply src/server/terrain/biomes.zig:23]: The simplest solution seems to be to create a new function for optionals.

I can't seem to figure out a cleaner way that keeps everything in one generalized function.

Comment (BoySanic) [reply src/server/terrain/biomes.zig:23]: Okay I pushed up an attempt at this. It feels wrong, though.

File: src/utils.zig [hunk 7]
```diff
@@ -2221,11 +2221,23 @@ fn CastFunctionSelfToAnyopaqueType(Fn: type) type {
 	typeInfo.@"fn".params = params[0..];
 	return @Type(typeInfo);
 }
+fn CastFunctionSelfToOptionalAnyopaqueType(Fn: type) type {
```
Comment (IntegratedQuantum) [inline src/utils.zig]: What would an optional self parameter mean, an how would it ever be useful?
Don't add functions that we don't need.

File: src/utils.zig [hunk 8]
```diff
@@ -2234,11 +2246,22 @@ fn CastFunctionReturnToAnyopaqueType(Fn: type) type {
 	typeInfo.@"fn".return_type = *anyopaque;
 	return @Type(typeInfo);
 }
+
+fn CastFunctionReturnToOptionalAnyopaqueType(Fn: type) type {
+	var typeInfo = @typeInfo(Fn);
+	if(@sizeOf(typeInfo.@"fn".return_type.?) != @sizeOf(?*anyopaque) or @alignOf(typeInfo.@"fn".return_type.?) != @alignOf(?*anyopaque) or @typeInfo(typeInfo.@"fn".return_type.?) != .optional) {
```
Comment (IntegratedQuantum) [inline src/utils.zig:2240]: Please also adjust the non-optional function to do the inverse check.

**Review by IntegratedQuantum — CHANGES_REQUESTED** [review]

File: src/server/terrain/structure_building_blocks.zig [hunk 9]
```diff
@@ -341,27 +341,23 @@ pub const StructureBuildingBlock = struct {
 pub fn registerSBB(structures: *Assets.ZonHashMap) !void {
 	std.debug.assert(structureList.items.len == 0);
 	std.debug.assert(structureMap.capacity() == 0);
-
-	structureList.resize(main.worldArena, structures.count());
```
Comment (Argmaster) [inline src/server/terrain/structure_building_blocks.zig:345]: Please add ensureCapacity call with structures.count() to ensure structureList never has to reallocate it's storage.

File: src/utils.zig (hunk 8 above)
Comment (BoySanic) [reply src/utils.zig:2240]: Done

File: src/utils.zig (hunk 7 above)
Comment (BoySanic) [reply src/utils.zig]: Removed

File: src/server/terrain/structure_building_blocks.zig (hunk 9 above)
Comment (BoySanic) [reply src/server/terrain/structure_building_blocks.zig:345]: Done

File: src/server/terrain/structure_building_blocks.zig [hunk 10]
```diff
@@ -341,27 +341,23 @@ pub const StructureBuildingBlock = struct {
...
 	defer childrenToResolve.deinit();
+	var loadedCount: u32 = 0;
 	{
 		var iterator = structures.iterator();
-		var index: u32 = 0;
 		while(iterator.next()) |entry| {
-			defer index += 1;
-
-			structureList.items[index] = StructureBuildingBlock.initFromZon(entry.key_ptr.*, entry.value_ptr.*) catch |err| {
+			structureList.append(main.worldArena, StructureBuildingBlock.initFromZon(entry.key_ptr.*, entry.value_ptr.*) catch |err| {
```
Comment (IntegratedQuantum) [inline src/server/terrain/structure_building_blocks.zig]: When you use ensureCapacity, please also use appendAssumeCapacity.

File: src/utils.zig [hunk 11]
```diff
@@ -2225,20 +2225,30 @@ fn CastFunctionSelfToAnyopaqueType(Fn: type) type {
 pub fn castFunctionSelfToAnyopaque(function: anytype) *const CastFunctionSelfToAnyopaqueType(@TypeOf(function)) {
 	return @ptrCast(&function);
 }
-
```
Comment (IntegratedQuantum) [inline src/utils.zig:2228]: Also please stop removing empty lines between blocks of funtions.

File: src/utils.zig [hunk 12]
```diff
@@ -2225,20 +2225,30 @@ fn CastFunctionSelfToAnyopaqueType(Fn: type) type {
...
+	}
+	typeInfo.@"fn".return_type = ?*anyopaque;
+	return @Type(typeInfo);
+}
 /// Turns the return parameter into a anyopaque*
 pub fn castFunctionReturnToAnyopaque(function: anytype) *const CastFunctionReturnToAnyopaqueType(@TypeOf(function)) {
 	return @ptrCast(&function);
 }
-
+pub fn castFunctionReturnToOptionalAnyopaque(function: anytype) *const CastFunctionReturnToOptionalAnyopaqueType(@TypeOf(function)) {
```
Comment (IntegratedQuantum) [inline src/utils.zig:2250]: These empty lines exist for a reason.

File: src/server/terrain/structure_building_blocks.zig [hunk 13]
```diff
@@ -342,26 +342,25 @@ pub fn registerSBB(structures: *Assets.ZonHashMap) !void {
 	std.debug.assert(structureList.items.len == 0);
 	std.debug.assert(structureMap.capacity() == 0);
 
-	structureList.resize(main.worldArena, structures.count());
+	structureList.ensureCapacity(main.worldArena, structures.count());
 	structureMap.ensureTotalCapacity(main.worldArena.allocator, structures.count()) catch unreachable;
 
 	childrenToResolve = .init(main.stackAllocator);
 	defer childrenToResolve.deinit();
+	var loadedCount: u32 = 0;
```
Comment (IntegratedQuantum) [inline src/server/terrain/structure_building_blocks.zig]: Why did you move this into the outer scope? Do you plan to use it somewhere below in the future?

Comment (BoySanic) [reply src/server/terrain/structure_building_blocks.zig]: I did originally but I don't really need that anymore. I'll revert that change.
