### PR TITLE
Prevent settings from breaking when no previous file is present.

### LINKED ISSUE #1718: The game cannot create a settings file if none is present
### Steps to Reproduce and Observed Behavior

This was caused by #1696 which now merges the existing file with the new one, merging fails if the existing file is not of type object. Other types should be handled and discarded if present

@codemob-dev could you fix this please, this is going to be quite problematic for new players

### PR DESCRIPTION
**Pull request by codemob-dev**
Fix #1718

### CODE REVIEW

File: src/settings.zig [hunk 1]
```diff
@@ -154,15 +153,20 @@ pub fn save() void {
...
 		break :blk .null;
 	};
 	defer oldZonObject.deinit(main.stackAllocator);
 
-	oldZonObject.join(zonObject);
+	if(oldZonObject == .object) {
+		oldZonObject.join(zonObject);
+	} else {
+		oldZonObject.deinit(main.stackAllocator);
+		oldZonObject = zonObject;
```
Comment (IntegratedQuantum) [inline src/settings.zig:169]: This will cause a double free, since now both the `oldZonObject` and the `zonObject` are deinited.

**Comment by codemob-dev** [comment]
This should work now

**Review by IntegratedQuantum — APPROVED** [review]
It does seem to work now
