### PR TITLE
Override glfw's keynames to distinguish between keys that print the same character

### LINKED ISSUE #2605: Keybind UI: Number row and number pad are not distinguished
### Steps to Reproduce and Observed Behavior

Image

on a full-sized keyboard, the label for the many characters in the number row and the number pad have the exact same label despite the game being able to read them as separate keys just fine.

### PR DESCRIPTION
**Pull request by BoySanic**
Fixes #2605

X11, Wayland, etc provide the printable character, not some other name that describes the key. So Keypad 1 and 1 come up as the same name but different scancodes. 

To fix this, I reordered `getName` so our table of names gets used first, and if we don't have the key defined ourselves, then it'll ask GLFW.

Updating GLFW would not have fixed this. The function does the same thing in the latest commit from what I can tell.
(And we're on the latest release of GLFW)

### CODE REVIEW

File: src/graphics/Window.zig [hunk 1]
```diff
@@ -439,7 +437,23 @@ pub const Key = struct { // MARK: Key
...
+				c.GLFW_KEY_KP_3 => "Keypad 3",
+				c.GLFW_KEY_KP_4 => "Keypad 4",
+				c.GLFW_KEY_KP_5 => "Keypad 5",
+				c.GLFW_KEY_KP_6 => "Keypad 6",
+				c.GLFW_KEY_KP_7 => "Keypad 7",
+				c.GLFW_KEY_KP_8 => "Keypad 8",
+				c.GLFW_KEY_KP_9 => "Keypad 9",
+				c.GLFW_KEY_KP_DECIMAL => "Keypad .",
+				c.GLFW_KEY_KP_DIVIDE => "Keypad /",
+				c.GLFW_KEY_KP_MULTIPLY => "Keypad *",
```
Comment (IntegratedQuantum) [inline src/graphics/Window.zig]: `*` does not show up, because it's a formatting character. Also on my keyboard it's a `×` and the `DECIMAL` is a `,`. So I'd suggest to keep the name as text for all the symbols, matching the GLFW string

File: src/graphics/Window.zig [hunk 2]
```diff
@@ -452,6 +466,16 @@ pub const Key = struct { // MARK: Key
 				c.GLFW_KEY_UNKNOWN => "(Unbound)",
 				else => "Unknown Key",
 			};
+			if (std.mem.eql(u8, key_name, "Unknown Key")) {
```
Comment (IntegratedQuantum) [inline src/graphics/Window.zig]: Just move this logic into the else case of the switch

**Review by IntegratedQuantum — CHANGES_REQUESTED** [review]

File: src/graphics/Window.zig (hunk 1 above)
Comment (BoySanic) [reply src/graphics/Window.zig]: So, I changed this to your suggestion. A side effect of doing this is that "Keypad Multiply" is too long for a single line, so it wants to wrap onto a 2nd line.

I'm thinking we either need to expand the button or shorten the name, because 2 lines for a single control when the rest take 1 seems odd.

I also like "Keypad" more than "KP" looking at the controls menu. But that's subjective.

For now I'll look at expanding the button width.

Comment (BoySanic) [reply src/graphics/Window.zig]: image
192 width works, but it's possible smaller values will work too. It was just the next multiple of 64 so I tried that.

Comment (IntegratedQuantum) [reply src/graphics/Window.zig]: Yeah I'd prefer it smaller. Maybe 160 could work

Comment (BoySanic) [reply src/graphics/Window.zig]: 160, indeed, worked.

I also moved the widths to constants so they're not magic numbers. (Though, it's not hard to figure out what they are. Just tedious to change them in a dozen places.)
