### PR TITLE
Fix #1457

### LINKED ISSUE #1457: "/set 0" causes a crash instead of erroring out.
Usually you get an error in the console if you type an invalid block name in a world edit command. However "/set 0" seems to be an exception.

Steps to reproduce:
1. Make a selection with the selection wand
2. Run /set 0

### PR DESCRIPTION
**Pull request by Argmaster**
Resolves: #1457

### CODE REVIEW

File: src/blueprint.zig [hunk 1]
```diff
@@ -336,26 +339,30 @@ pub const Pattern = struct {
...
 
 		while(specifiers.next()) |specifier| {
-			var iterator = std.mem.splitScalar(u8, specifier, '%');
+			var blockId = specifier;
+			var weight: f32 = 1.0;
 
-			var weight: f32 = undefined;
-			var block = main.blocks.parseBlock(iterator.rest());
+			if(std.mem.containsAtLeastScalar(u8, specifier, 1, weightSeparator)) {
+				var iterator = std.mem.splitScalar(u8, specifier, '%');
```
Comment (IntegratedQuantum) [inline src/blueprint.zig:353]: If you add a named constant for it, please use it consistently
```suggestion
				var iterator = std.mem.splitScalar(u8, specifier, weightSeparator);
```

File: src/blueprint.zig [hunk 2]
```diff
@@ -336,26 +339,30 @@ pub const Pattern = struct {
...
+				const weightString = iterator.next() orelse return error.MissingWeight;
```
Comment (IntegratedQuantum) [inline src/blueprint.zig:354]: Could still use `.first`, which cannot error.

File: src/blueprint.zig [hunk 3]
```diff
@@ -336,26 +339,30 @@ pub const Pattern = struct {
...
+				blockId = iterator.next() orelse return error.MissingBlockId;
```
Comment (IntegratedQuantum) [inline src/blueprint.zig:355]: Could still use `.rest`, which cannot error.

File: src/blueprint.zig [hunk 4]
```diff
@@ -336,26 +339,30 @@ pub const Pattern = struct {
...
 
-			const first = iterator.first();
+				if(iterator.next() != null) return error.TooManyElements;
```
Comment (IntegratedQuantum) [inline src/blueprint.zig:357]: Not needed, will be catched by invalid id path.

File: src/blueprint.zig [hunk 5]
```diff
@@ -336,26 +339,30 @@ pub const Pattern = struct {
...
+
+				weight = std.fmt.parseFloat(f32, weightString) catch return error.InvalidWeight;
+				if(weight <= 0) continue;
```
Comment (IntegratedQuantum) [inline src/blueprint.zig:360]: Should probably return InvalidWeight as well, instead of silently succeeding which invites the next bug (empty blockEntries list).

File: src/blueprint.zig (hunk 4 above)
Comment (Argmaster) [reply src/blueprint.zig:357]: Giving rather poor error message.

File: src/blueprint.zig [hunk 6]
```diff
@@ -336,26 +339,28 @@ pub const Pattern = struct {
...
+
+			if(std.mem.containsAtLeastScalar(u8, specifier, 1, weightSeparator)) {
+				var iterator = std.mem.splitScalar(u8, specifier, weightSeparator);
+				const weightString = iterator.first();
+				blockId = iterator.rest();
 
-			var weight: f32 = undefined;
-			var block = main.blocks.parseBlock(iterator.rest());
+				weight = std.fmt.parseFloat(f32, weightString) catch return error.@"Weight not a valid number";
+				if(weight <= 0) return error.@"Weight must be >= 0";
```
Comment (IntegratedQuantum) [inline src/blueprint.zig:358]: Should be >, also is not intended for programmers, so better use english words instead
```suggestion
				if(weight <= 0) return error.@"Weight must be greater than 0";
```

**Review by IntegratedQuantum — CHANGES_REQUESTED** [review]

**Review by IntegratedQuantum — APPROVED** [review]
