### PR TITLE
Hide gui

### LINKED ISSUE #2343: When the GUI is hidden and ESC is pressed the GUI is still hidden
### Steps to Reproduce and Observed Behavior

Press F1 to hide GUI
Press ESC to show inventory.
Result -> Nothing to see, only your mouse

I can see the idea that this could be not a bug but a feature but I at least would like it more if it would then show my inventory etc

### LINKED ISSUE #2448: When the gui is hidden you can stil write in the chat without realizing it
### Steps to Reproduce and Observed Behavior

Press F1 or whatever key hides the gui.
Press t to open chat.

Observed Behavior: you write but don't see what
Expected Behavior: you cannot write at all (or other solutions)

### PR DESCRIPTION
**Pull request by Wunka**
Fixes: #2343 
fixes #2448

### CODE REVIEW

**Review by IntegratedQuantum — CHANGES_REQUESTED** [review]
Should this behavior maybe apply to all menu keys (inventory, creative inventory, chat, ...)? In that case I think it should be added to the toggleGameMenu function.

**Comment by Wunka** [comment]
> Should this behavior maybe apply to all menu keys (inventory, creative inventory, chat, ...)? In that case I think it should be added to the toggleGameMenu function.

I don't quite understand what you mean.. But while I looked at this I found that the guis are only hidden but you can still write in the chat. I will open an Issue for that

**Comment by IntegratedQuantum** [comment]
> I don't quite understand what you mean..

If you press `t` to open chat, or `e` to open inventory, then maybe we should also unhide the GUI, since you likely want to go to the inventory or chat, but you cannot see it if it's hidden.

**Comment by Wunka** [comment]
Would this then not go against why we wanted to only ESC have this function? Reference: https://github.com/PixelGuys/Cubyz/issues/2343#issuecomment-3589986110

**Comment by IntegratedQuantum** [comment]
Well, for taking the screenshot you could still hide the gui again with F1 when you are in the inventory/menu.

**Comment by Wunka** [comment]
done

**Comment by Wunka** [comment]
there is some wierd bug for me now. So please wait

**Comment by Wunka** [comment]
removed the return. Now it unhides and opens inventory chat etc at the same time, but else there would be many cases where I would need to put the if(hideGui). Example for when opening the chat. Now #2448 is fixed but you can still hide the gui while writing in the chat

File: src/gui/gui.zig [hunk 1]
```diff
@@ -568,6 +568,9 @@ pub fn updateAndRenderGui() void {
 }
 
 pub fn toggleGameMenu() void {
+	if(hideGui) {
+		hideGui = false;
```
Comment (IntegratedQuantum) [inline src/gui/gui.zig]: I think it should only do this when the menu wasn't open already.
Also the if is kind of unnecessary.

**Review by IntegratedQuantum — CHANGES_REQUESTED** [review]

File: src/gui/gui.zig (hunk 1 above)
Comment (Wunka) [reply src/gui/gui.zig]: done

**Review by IntegratedQuantum — APPROVED** [review]
