### PR TITLE
Use the actual block model when calculating block selection

### LINKED ISSUE #2123: Can't place blocks through gaps
### Steps to Reproduce and Observed Behavior

when you use the chisel tool you cannot place blocks through the gaps you create. 

Image

https://www.youtube.com/watch?v=gtY5IgYjhH8&lc=UgwPOxGxgtHgAAHQC1N4AaABAg

12:01

### PR DESCRIPTION
**Pull request by codemob-dev**
image

Fixes #2123

### CODE REVIEW

File: src/rotation.zig [hunk 1]
```diff
@@ -61,33 +61,35 @@ pub const RotationMode = struct { // MARK: RotationMode
...
+					} else if(boxTMin == t2[0]) {
+						face = Neighbor.dirPosX;
+					} else if(boxTMin == t2[1]) {
+						face = Neighbor.dirPosY;
+					} else if(boxTMin == t2[2]) {
+						face = Neighbor.dirUp;
+					} else {
+						unreachable;
+					}
+					return .{
```
Comment (OneAvargeCoder193) [inline src/rotation.zig]: This doesn't seem to find the closest block the ray intersects with, but the first

Comment (codemob-dev) [reply src/rotation.zig]: Hmm, that makes sense. Does it matter though?

Comment (codemob-dev) [reply src/rotation.zig]: Actually it does, nevermind

**Review by IntegratedQuantum — CHANGES_REQUESTED** [review]
The collision model is deliberately imprecise. I think it would make more sense to use the actual quad model instead.

**Comment by codemob-dev** [comment]
> I think it would make more sense to use the actual quad model instead.

Sure, I'll try that.

**Comment by codemob-dev** [comment]
> The collision model is deliberately imprecise. I think it would make more sense to use the actual quad model instead.

Done!

**Comment by IntegratedQuantum** [comment]
please use a descriptive title

**Comment by codemob-dev** [comment]
> please use a descriptive title

Done.

File: src/rotation.zig [hunk 2]
```diff
@@ -57,37 +57,34 @@ pub const RotationMode = struct { // MARK: RotationMode
...
+				if(rayTriangleIntersection(relativePlayerPos, playerDir, triangle1)) |distance| {
+					if(minimum == null or distance < minimum.?) {
+						minimum = distance;
+						face = Neighbor.fromVec(f32, quad.normalVec());
+					}
+				}
+				if(rayTriangleIntersection(relativePlayerPos, playerDir, triangle2)) |distance| {
+					if(minimum == null or distance < minimum.?) {
+						minimum = distance;
+						face = Neighbor.fromVec(f32, quad.normalVec());
```
Comment (IntegratedQuantum) [inline src/rotation.zig]: I think we should rethink what this face value is used for and how we can make it more usable than just taking a wild approximation, which I'm sure is going to cause unexpected behavior everywhere (e.g. consider the cross model).

**Review by IntegratedQuantum — CHANGES_REQUESTED** [review]

File: src/rotation.zig (hunk 2 above)
Comment (codemob-dev) [reply src/rotation.zig]: Perhaps we could leave it null if it isn't accurate enough?

Comment (codemob-dev) [reply src/rotation.zig]: Then the code that uses it could choose to use the player position relative to the block instead if needed.

Comment (IntegratedQuantum) [reply src/rotation.zig]: What exactly is it even used for? Could we maybe just remove this parameter and replace it with a better approach (like the proposed player looking direction)?

Comment (codemob-dev) [reply src/rotation.zig]: > What exactly is it even used for? Could we maybe just remove this parameter and replace it with a better approach (like the proposed player looking direction)?

It is used when placing blocks to check which face of the selected block the new block should be placed off of. I don't think using the player looking direction is a good idea for this.

Comment (IntegratedQuantum) [reply src/rotation.zig]: No, that cannot be true. The new block is placed based on the whole block volume, otherwise placing carpets wouldn't work like it does.

Comment (codemob-dev) [reply src/rotation.zig]: > No, that cannot be true. The new block is placed based on the whole block volume, otherwise placing carpets wouldn't work like it does.

Oh, nevermind. It's only used in renderer.zig line 1116 for item drops.

Comment (IntegratedQuantum) [reply src/rotation.zig]: Ah, for item drops it should probably use the full normal then.

Comment (codemob-dev) [reply src/rotation.zig]: Done

File: src/Inventory.zig [hunk 3]
```diff
@@ -1770,14 +1770,14 @@ pub const Command = struct { // MARK: Command
...
 			}
-			inline fn major(self: BlockDropLocation) Vec3d {
-				return @floatFromInt(@abs(self.dir.relPos()));
+			inline fn major(self: BlockDropLocation) Vec3f {
+				return @abs(self.normalDir);
 			}
-			inline fn minor(self: BlockDropLocation) Vec3d {
-				return @floatFromInt(self.dir.orthogonalComponents());
+			inline fn minor(self: BlockDropLocation) Vec3f {
+				return Vec3f{1.0, 1.0, 1.0} - @abs(self.normalDir);
```
Comment (IntegratedQuantum) [inline src/Inventory.zig]: Since the normal is arbitrary, the minor directions now should return two vectors and the randomization code should be adjusted accordingly.

File: src/rotation.zig [hunk 4]
```diff
@@ -176,6 +177,39 @@ pub fn rotationMatrixTransform(quad: *main.models.QuadInfo, transformMatrix: Mat
 	}
 }
 
+fn rayTriangleIntersection(origin: Vec3f, direction: Vec3f, triangle: [3]Vec3f) ?f32 {
```
Comment (IntegratedQuantum) [inline src/rotation.zig:191]: If you use copy pasted code (which I assume you did here), then please link the source.

**Review by IntegratedQuantum — CHANGES_REQUESTED** [review]

File: src/Inventory.zig (hunk 3 above)
Comment (codemob-dev) [reply src/Inventory.zig]: Done

File: src/Inventory.zig [hunk 5]
```diff
@@ -1765,19 +1765,24 @@ pub const Command = struct { // MARK: Command
 			}
 			fn outsidePos(self: BlockDropLocation, _pos: Vec3i) Vec3d {
 				const pos: Vec3d = @floatFromInt(_pos);
-				return pos + self.randomOffset()*self.minor() + self.directionOffset()*self.major() + self.direction()*itemHitBoxMarginVec;
+				const minorValues = minors(self);
+				const minor1Offset = @as(Vec3f, @splat(vec.dot(self.randomOffset(), minorValues[0])))*minorValues[0];
+				const minor2Offset = @as(Vec3f, @splat(vec.dot(self.randomOffset(), minorValues[1])))*minorValues[1];
```
Comment (IntegratedQuantum) [inline src/Inventory.zig]: I think both of these should reuse the same randomOffset, otherwise the resulting vector may end up outside the desired box.

File: src/Inventory.zig [hunk 6]
```diff
@@ -1765,19 +1765,24 @@ pub const Command = struct { // MARK: Command
 			}
 			fn outsidePos(self: BlockDropLocation, _pos: Vec3i) Vec3d {
 				const pos: Vec3d = @floatFromInt(_pos);
-				return pos + self.randomOffset()*self.minor() + self.directionOffset()*self.major() + self.direction()*itemHitBoxMarginVec;
+				const minorValues = minors(self);
```
Comment (IntegratedQuantum) [inline src/Inventory.zig]: value suggest a scalar
```suggestion
				const minorVectors = minors(self);
```

File: src/Inventory.zig [hunk 7]
```diff
@@ -1765,19 +1765,24 @@ pub const Command = struct { // MARK: Command
...
 			}
-			inline fn major(self: BlockDropLocation) Vec3d {
-				return @floatFromInt(@abs(self.dir.relPos()));
+			inline fn major(self: BlockDropLocation) Vec3f {
+				return @abs(self.normalDir);
 			}
-			inline fn minor(self: BlockDropLocation) Vec3d {
-				return @floatFromInt(self.dir.orthogonalComponents());
+			inline fn minors(self: BlockDropLocation) struct {Vec3f, Vec3f} {
+				const minor1 = vec.cross(self.normalDir, if( @reduce(.And, @abs(self.normalDir) == Vec3f{1.0, 0.0, 0.0})) Vec3f{0.0, 1.0, 0.0} else Vec3f{1.0, 0.0, 0.0});
```
Comment (IntegratedQuantum) [inline src/Inventory.zig]: The result should be normalized, since the vectors of the cross product do not have a 90° angle.

**Review by IntegratedQuantum — CHANGES_REQUESTED** [review]

**Review by IntegratedQuantum — CHANGES_REQUESTED** [review]
Please rebase to include the sync refactor

**Comment by codemob-dev** [comment]
> Please rebase to include the sync refactor

Done!

**Review by IntegratedQuantum — APPROVED** [review]
Looks good, only thing that bothers me is that you cannot select through the transparent pixels in e.g. the flower meshes, but that's a bigger topic, so I made an issue for it: #2939
